image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
  MAVEN_IMAGE: maven:3-openjdk-11-slim:latest
  APP_IMAGE: users-app
  APP_TAG: $CI_COMMIT_TAG

stages:
  - build
  - itests

# Packaging the project with JUnit tests running
maven-build:
  stage: build
  image: $MAVEN_IMAGE
  script:
    - mvn package -B
  artifacts:
    paths:
      - target/*.jar

# Starting integration tests that use docker testcontainers
maven-integration-tests:
  stage: itests
  image: $MAVEN_IMAGE
  script:
    - mvn verify -Pintegration-test