concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-win64-runner"
  url = "https://gitlab.com/"
  id = 20781651
  token = "ibHVYnQRyAAs4TkfRb5H"
  token_obtained_at = 2023-01-31T06:49:50Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker-windows"
  shell = "pwsh"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3-openjdk-11-slim:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["c:\\cache"]
    shm_size = 0

[[runners]]
  name = "gitlab-win64-local"
  url = "https://gitlab.com/"
  id = 20785200
  token = "MDTibDLxyFV4uGQ9qzdY"
  token_obtained_at = 2023-01-31T09:31:41Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "instance"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
